### ISSUE TITLE
[Question] More complex navigation application

### ISSUE THREAD

**Issue by blyscuit** [lngyeen/MySurveyChallenge#36]
## Issue

How would you design an application with more complex navigation?

Examples:

- Pushing or popping two or more screens at once.
- Pushing that is not pre-set and determined by API response.
- Multiple entries to a particular screens.
- Tab bar with individual navigation stacks.
- Push navigation inside modal navigation.

**Comment by lngyeen** [comment]
**_In UIKit:_**

- Pushing or popping two or more screens at once. => I can modify UINavigationController's viewControllers array to push multi screens, and then setViewControllers(_ :, animated:). To pop i can use popToViewController(_; animated) to pop multiple screens at once.

- Pushing that is not pre-set and determined by API response. => Easy to do in UIKit with imperative style.

- Multiple entries to a particular screens.  => 

To be reusable we can implement a Factory pattern so when we push/modal a new UIViewController we can use that Factory to init and setup data for new UIViewController before pushing. 
In my current project i apply a new pattern like this:
 
```
protocol BindableType: AnyObject {
    associatedtype ViewModelType
    var viewModel: ViewModelType! { get set }
    func bindViewModel()
}

extension BindableType where Self: UIViewController {
    func bindViewModel(to model: Self.ViewModelType, nibLoaded: Bool = false) {
        viewModel = model
        if !nibLoaded {
            loadViewIfNeeded()
        }
        bindViewModel()
    }
}

extension BindableType where Self: UIView {
    func bindViewModel(to model: Self.ViewModelType) {
        viewModel = model
        bindViewModel()
    }
}

import Foundation

struct Treatments: Flow {
    let scene: Scene
    init(scene: TreatmentsScene) {
        self.scene = scene
    }
}

enum TreatmentsScene: Scene {
    case treatmentPlanDetails(TreatmentPlanDetailsViewModel)
    case treatmentPeriodDetails(TreatmentPeriodDetailsViewModel)
    case recommendationDetails(RecommendationDetailsViewModel)
}

extension TreatmentsScene {
    func viewController() -> UIViewController {
        switch self {
        case let .treatmentPlanDetails(viewModel):
            let vc = TreatmentPlanDetailsViewController()
            vc.bindViewModel(to: viewModel)
            return vc

        case let .treatmentPeriodDetails(viewModel):
            let vc = TreatmentPeriodDetailsViewController()
            vc.bindViewModel(to: viewModel)
            return vc

        case let .recommendationDetails(viewModel):
            let vc = RecommendationDetailsViewController()
            vc.bindViewModel(to: viewModel)
            return vc
        }
    }
}
```

and then push/modal new screen like this:
```
let sceneCoordinator = SceneCoordinator(navigationController: navigationController)
let vm = ViewModel()
sceneCoordinator.transitionTo(flow: Treatments(scene: .treatmentPlanDetails(vm)),
                                      type: .push(hidesBottomBarWhenPushed: true))
```

- Tab bar with individual navigation stacks.  => In UIKit with UITabBarController and each tab is a 

contains UINavigationController.

- Push navigation inside modal navigation. => We can push a new screen inside modal UINavigationController easily in UIKit. Inside the UIViewController, just init a new UIViewController and push to existing UINavigationController.

**_In SwiftUI:_** To be honest, I haven't studied SwiftUI very deeply, so I'll answer these parts based on my limited knowledge. I will try to update in the near future :)

- Pushing or popping two or more screens at once. => with NavigationLink (iOS <= 15) we could not do that but with new NavigationStack(iOS 16+) we can do it with NavigationStack and NavigationPath
- Pushing that is not pre-set and determined by API response. => With NavigationView we can use a @ViewBuilder to do some logic and return a destination view or a NavigationLink, but with NavigationStack it more easy with `.navigationDestination(for:`
- Multiple entries to a particular screens. => In SwiftUI i think it will be simple, no need any pattern since we can init and put the View as a destination of a NavigationView/NavigationStack with clear and simple swiftUI API.
- Tab bar with individual navigation stacks. => In SwiftUI we can use TabView and inside each TapItem just put a NavigationView/NavigationStack
- Push navigation inside modal navigation. => In SwiftUI i think we can do this easily, modal a new NavigationView/NavigationStack and navigate inside it.
