### ISSUE TITLE
[Question] Improve code coverage

### ISSUE THREAD

**Issue by blyscuit** [lngyeen/MySurveyChallenge#37]
## Issue

- What are your experience with UI Test?

- How would you implement a UI test to cover one of the two cases:

1. User has token and see a survey.
    1. 1.1 User can scroll to the right to see the next survey.
2. User did not log in
    1. 2.1 User fill email and password field
    2. 2.2 User tap the `Log in` button.

- Make sure that the test is successful on a separate run. The test should not affect data stored on the application on the same device/simulator.

- What is the decision to not include unit test to `AuthenticationManagerImpl`?

**Comment by lngyeen** [comment]
@blyscuit 

- What are your experience with UI Test? => Yes, I do write UI Tests for the projects we work on but long time we did not do it since we have automation tester. There are frameworks that support UITest like XCUITest from Apple, KIF and other frameworks like Appium...
- How would you implement a UI test to cover one of the two cases: I'll try writing them using KIF.
- What is the decision to not include unit test to AuthenticationManagerImpl? => Sorry, maybe I forgot to write a test for it :(

**Comment by lngyeen** [comment]
@blyscuit Sorry, I tried KIF with SwiftUI but it seems the KIF API doesn't work well with SwiftUI (I'm very able to get elements via accessibilityLabel). So I tried with XCUITest, you can see through this PR: https://github.com/lngyeen/MySurveyChallenge/pull/48
